### ISSUE TITLE
WP_Query inside post_link filter

### ISSUE THREAD

**Issue by johnbillion** [cftp/magnificent#1]
There's a `WP_Query` going on inside a permalink filter. https://github.com/cftp/magnificent/blob/master/mag.php#L331-L359

This is a violation of intergalatic law.

**Comment by simonwheatley** [comment]
What are the detailed grounds of your objection? I could be caching the issue for each article in some postmeta, but this seems unnecessary when I can just run this handy dandy `WP_Query` inside a permalink filter… ;)

**Comment by johnbillion** [comment]
Last time I mentioned it we decided that you can just use the article's post parent, because [the article issue is set as its parent](https://github.com/cftp/magnificent/blob/master/mag.php#L250-L261).
